name: 'Claude Code Test Runner'
description: 'Run automated tests using Claude Code with Playwright integration via Docker'
author: 'Your Name'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  anthropic-api-key:
    description: 'Anthropic API key for Claude Code'
    required: true
  test-config:
    description: 'Path to test configuration file'
    required: false
    default: './test.ts'
  results-path:
    description: 'Path to store test results (mounted as volume)'
    required: false
    default: './test-results'
  timeout:
    description: 'Test timeout in minutes'
    required: false
    default: '30'

outputs:
  test-results-path:
    description: 'Path to generated test results'
    value: ${{ steps.run-tests.outputs.results-path }}
  tests-passed:
    description: 'Number of tests that passed'
    value: ${{ steps.run-tests.outputs.passed }}
  tests-failed:
    description: 'Number of tests that failed'
    value: ${{ steps.run-tests.outputs.failed }}
  ctrf-report:
    description: 'Path to CTRF JSON report'
    value: ${{ steps.run-tests.outputs.ctrf-report }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
    TEST_CONFIG: ${{ inputs.test-config }}
    RESULTS_PATH: ${{ inputs.results-path }}
    TIMEOUT_MINUTES: ${{ inputs.timeout }}
  args:
    - ${{ inputs.test-config }}
    - ${{ inputs.results-path }}